Allow for ruby 3.1 kwarg syntax
BiggerPockets/patterns pull request #119
Opened 2022-08-12 20:24 UTC by bockets

2022-08-12 20:33 UTC, lautarol approved these changes

2022-08-15 09:14 UTC, karlentwistle approved these changes

2022-08-18 08:51 UTC, johngallagher requested changes
~I'm not keen on this new syntax - I think it'll hide problems. I think we need a wider discussion with everyone.~

I was going to use the argument "we don't slavishly follow every change to Ruby"...

But then looking down [the evolution of Ruby](https://rubyreferences.github.io/rubychanges/evolution.html) (great reference BTW) I can see very few changes that I wouldn't use or encourage.

I'm not keen on the new syntax but maybe I just need to get used to it. Still - seems a bit magical and we need to be careful that we're not using it as a crutch - lots of instance variables are a smell. So cautiously approving.

2022-08-18 09:03 UTC, johngallagher submitted a review, later dismissed

2022-08-23 15:36 UTC, kxhitiz approved these changes
I have the same hesitation as John's. But I am open to go with this pattern.

2022-08-31 13:44 UTC, baerbradford submitted a review, later dismissed

2022-08-31 15:23 UTC, BPMattBauer approved these changes

2022-08-31 15:24 UTC, RenatoCoelho-BiggerPockets approved these changes

2022-08-31 15:24 UTC, Hafiz-ahmed-dev approved these changes

2022-09-01 08:42 UTC, RenatoCoelho-BiggerPockets approved these changes

2022-09-01 16:11 UTC, johngallagher approved these changes

2022-09-01 16:22 UTC, cernivec approved these changes

2022-09-23 15:36 UTC, sogamoso approved these changes
I'm hesitant about this change. I don't particularly love the new syntax, but It may grow on me with time. Let's give it a chance.

2022-09-23 16:05 UTC, RajaaBoulassouak approved these changes

2022-09-26 15:59 UTC, Hafiz-ahmed-dev approved these changes

2022-09-26 16:01 UTC, merged