Namespacing for apps and events
BiggerPockets/patterns pull request #135
Opened 2022-10-31 15:33 UTC by johngallagher

2022-11-07 20:38 UTC, bockets commented on _patterns/use-namespacing-for-apps.md
> +* Allows targeting all tools, all content apps using wildcards like `tools.*`
```suggestion
* Allows targeting all tools, all platform apps using wildcards like `tools.*`
```

2022-12-19 16:40 UTC, RenatoCoelho-BiggerPockets approved these changes

2022-12-19 16:53 UTC, bhanubhakta approved these changes

2022-12-19 16:59 UTC, cernivec approved these changes

2022-12-19 21:17 UTC, sogamoso requested changes
@johngallagher, thanks for working on this. I think that well organized code is important and I agree that having clearer boundaries via namespace will probably help with that.

Nonetheless, it's not clear to me how those namespaces should be used. Are these concepts meant to be used for code organization or event naming? It would be great if we had a place where we could find a list (it can just be folder names in the codebase) of all the namespaces so that anyone can quickly figure out if they should put new code on an existing namespace or create a new one.

2023-02-01 07:32 UTC, sogamoso approved these changes
@johngallagher, thanks for making the intention clearer. Your changes answered my questions.

2023-02-27 16:43 UTC, bockets approved these changes

2023-03-07 17:25 UTC, kxhitiz commented on _patterns/use-namespacing-for-apps.md
> +* `marketplace.agent_finder.searching.search.performed` - agent finder is complex, so we break it up into bounded contexts. This is a search being performed within the investor facing `searching` bou
This is great John. I have a question about how the event name shows up in the amplitude. 

For this specific event in the above example `marketplace.agent_finder.searching.search.performed`, looks all good with the namespacing to see where the event is triggered from. 
But in amplitude, it will show up as `Search Performed` as seen [here](https://analytics.amplitude.com/biggerpockets/chart/new/k8327jj). So anyone who directly goes to amplitude just sees `Search Performed` and is hard to tell where this search happened right? Or is there any way in amplitude to see the context?

2023-03-27 16:37 UTC, johngallagher commented on _patterns/use-namespacing-for-apps.md
> +* `marketplace.agent_finder.searching.search.performed` - agent finder is complex, so we break it up into bounded contexts. This is a search being performed within the investor facing `searching` bou
Really good point @kxhitiz - it turns out it's possible to port these namespaces over to Amplitude as a custom property.

<img width="879" alt="image" src="https://user-images.githubusercontent.com/22185/228006810-706d287d-ce18-4e36-99f3-3beaccd42685.png">

However, this isn't possible with the current Amplitude setup. It requires us to upgrade our Amplitude destination which I'll do as part of the UTM tracking work.

2023-03-27 16:38 UTC, merged

2023-04-20 15:22 UTC, DyegoCosta commented on _patterns/use-namespacing-for-apps.md
> +* `marketplace.agent_finder.searching.search.performed` - agent finder is complex, so we break it up into bounded contexts. This is a search being performed within the investor facing `searching` bou
Is this still an issue? Seems like this is a real blocker for using this event namespacing pattern. I tried to follow it [here](https://github.com/BiggerPockets/biggerpockets/pull/17690#discussion_r1171536848) but will face the same limitation with Amplitude. Do we have something planned to address this? I might need to not follow this pattern in order to make it work well in Amplitude.