Make Sidekiq workers small and atomic
BiggerPockets/patterns pull request #138
Opened 2022-11-22 15:15 UTC by johngallagher

2022-11-22 15:49 UTC, karlentwistle commented on _patterns/make-small-atomic-sidekiq-workers.md
> +        end
Maybe its too much detail but example but this code would be more performant if it used `pluck(:id)`, for example something like:

```ruby
::Companies::LeadBundleSubscription.with_pause_start_date.in_the_past.in_batches.each do |subscriptions_batch|
  subscriptions_batch.pluck(:id).each do |subscription_id|
    ActivateJob.perform_async(subscription_id)
  end
end
```

It's also possible to use Batch Jobs 

```ruby
::Companies::LeadBundleSubscription.with_pause_start_date.in_the_past.in_batches.each do |subscriptions_batch|
  batch = Sidekiq::Batch.new
  batch.jobs do
    subscriptions_batch.pluck(:id).each do |subscription_id|
      ActivateJob.perform_async(subscription_id)
    end
  end
end
```

I guess I'm wondering if its worth fleshing this one out a bit since its considered the "Best"

2022-11-22 15:51 UTC, karlentwistle approved these changes
Agree with the advice, just had a comment about the implementation details of best

2022-11-22 16:04 UTC, RenatoCoelho-BiggerPockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +We had a [serious issue](https://www.notion.so/biggerpockets/Lead-bundle-subscriptions-incorrectly-pausing-or-resuming-298e9b328c834b148e3c79f12a686004) where users' subscriptions were not being upda
```suggestion
We had a [serious issue](https://www.notion.so/biggerpockets/Lead-bundle-subscriptions-incorrectly-pausing-or-resuming-298e9b328c834b148e3c79f12a686004) where user subscriptions were not being updated.
```

English is not my first language so this correction might be wrong.

2022-11-22 16:04 UTC, RenatoCoelho-BiggerPockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +          next unless lead_bundle_subscription.pause_start_date # This will make a huge database query, only to discard 90% of the records!
I suggest you put the comment on the line before, so its more readable, just like you did below.

2022-11-22 16:09 UTC, RenatoCoelho-BiggerPockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +    class StartStopPauseLeadBundleSubscriptionJob
_Pet peeve_
Seems more readable to me if have the `StartStopPauseJob` before the `StartStopPauseLeadBundleSubscriptionJob`.

2022-11-22 16:15 UTC, RenatoCoelho-BiggerPockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +    class StartStopPauseJob
```suggestion
    class PauseUnpauseJob
```
The original name is making this harder to read for me. I'm proposing you change it for this pattern not necessarily go change the code.

2022-11-22 16:18 UTC, RenatoCoelho-BiggerPockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +    class StartStopPauseJob
```suggestion
    class PauseOrActiveJob
```

2022-12-05 16:19 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +    class StartStopPauseLeadBundleSubscriptionJob
There are many, many things wrong with the namespacing of these modules. I've chosen to move past those naming issues as it's not part of the pattern.

If I were doing this correctly, I'd do this - `app namespace` -> `app` -> `domain object` -> `action`

```ruby
module Marketplace
  module AgentFinder
     module LeadBundleSubscription
       class UpdateActivationStatusJob
```

2022-12-05 16:34 UTC, RenatoCoelho-BiggerPockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +    class StartStopPauseLeadBundleSubscriptionJob
My comment is not regarding namespacing, the `StartStopPauseLeadBundleSubscriptionJob` and `StartStopPauseJob` classes are in the same scope. I think its easier to understand what's going on if we first see `StartStopPauseJob`.
But as I said before it's just a pet peeve, feel free to leave it as is if you don't agree.

2022-12-09 13:57 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +    class StartStopPauseLeadBundleSubscriptionJob
I see what you mean now! Great call. Funnily enough I was getting confused **reading my own examples** and your tip made it much easier. c2b31b8d74ec29c28b55f0cd4d454b42a0701d60

2022-12-09 13:59 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +    class StartStopPauseJob
2b2fbcbe6e4f5e99ec6a4b01351933bab86e4570

2022-12-09 13:59 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +    class StartStopPauseJob
2b2fbcbe6e4f5e99ec6a4b01351933bab86e4570

2022-12-09 14:00 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +          next unless lead_bundle_subscription.pause_start_date # This will make a huge database query, only to discard 90% of the records!
Done.

2022-12-09 14:00 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +        end
Super cool suggestions @karlentwistle - thank you. Updated!

2022-12-09 14:07 UTC, cernivec approved these changes

2022-12-09 14:20 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +            end
This uses only one network roundtrip, so the job will complete faster:

```suggestion
            ActivateJob.push_bulk(subscriptions_batch.pluck(:id))
```

2022-12-09 14:22 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +            end
```suggestion
            PauseJob.perform_bulk(subscriptions_batch.pluck(:id).zip)
```

2022-12-09 14:24 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +    class StartStopPauseJob
I don't think that including the namespaces adds to the point that you're trying to make, and seem a bit like a distracting detail.

2022-12-09 14:25 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +        end
StartStopPauseSubscriptionJob.perform_bulk(::Companies::LeadBundleSubscription.with_pause_start_date.ids.zip)

2022-12-09 14:26 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +        end
```suggestion
        StartStopPauseSubscriptionJob.perform_bulk(::Companies::LeadBundleSubscription.with_pause_start_date.ids.zip)
```

2022-12-09 14:28 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +          batch.jobs do
should this be subscription batches to match line 84?

2022-12-09 14:29 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +        ::Companies::LeadBundleSubscription.with_pause_start_date.in_the_past.in_batches do |subscriptions_batch|
I recommend `find_each` rather than `in_batches`, especially since you're just looping through the batch, which is what `find_each` does.

2022-12-09 14:31 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +        end
The error handler does nothing, yea?

```suggestion
        # Again, #activate! is more descriptive than #unpause!
        ::Companies::LeadBundleSubscription.find_by(id: lead_bundle_subscription_id)&.activate!
```

2022-12-09 14:32 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +    # Much better name. The opposite of pausing is activating.
This comment is very subjective. Naming is hard.

2022-12-09 14:41 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +            end
Woah! I'm learning sooo much about how to do things more efficiently... ❤️ thank you!

2022-12-09 14:41 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +    class StartStopPauseJob
Agreed. Good point. I'll cut the fat.

2022-12-09 14:42 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +          batch.jobs do
Nope. It's the API for [Sidekiq Batch Jobs](https://github.com/BiggerPockets/biggerpockets/pull/16629#pullrequestreview-1211732652)

2022-12-09 14:43 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +    # Much better name. The opposite of pausing is activating.
Hmmm... not sure I agree but it's controversial so I'll take it out.

2022-12-09 14:44 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +        end
I don't understand your comment... yup, the handler catches record not found... do you mean I should exclude this for clarity?

2022-12-09 14:45 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +        ::Companies::LeadBundleSubscription.with_pause_start_date.in_the_past.in_batches do |subscriptions_batch|
Although @karlentwistle gave me the exact opposite advice... @karlentwistle - maybe chime in here on your reasoning behind `#in_batches` ? I'm not precious either way TBH.

2022-12-09 14:48 UTC, karlentwistle commented on _patterns/make-small-atomic-sidekiq-workers.md
> +        ::Companies::LeadBundleSubscription.with_pause_start_date.in_the_past.in_batches do |subscriptions_batch|
Oh, its because we want to do `subscriptions_batch.pluck(:id)` and I don't think possible with `find_each` https://discuss.rubyonrails.org/t/feature-proposal-use-find-each-find-in-batches-with-pluck/70764/6

2022-12-09 14:55 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +        end
f02a69a9c48fa193889900ccd23bf863e4eca0fc

2022-12-09 14:55 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +          batch.jobs do
Don't need this now we're doing `#perform_bulk`...

2022-12-09 14:56 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +        ::Companies::LeadBundleSubscription.with_pause_start_date.in_the_past.in_batches do |subscriptions_batch|
I think the reason @bockets thinking about this was that we're doing a `#perform_bulk` so it makes sense to do that on batches...

2022-12-09 14:56 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +            end
f02a69a9c48fa193889900ccd23bf863e4eca0fc

2022-12-09 14:57 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +    # Much better name. The opposite of pausing is activating.
f02a69a9c48fa193889900ccd23bf863e4eca0fc

2022-12-09 14:57 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +            end
f02a69a9c48fa193889900ccd23bf863e4eca0fc

2022-12-09 15:00 UTC, Hafiz-ahmed-dev approved these changes

2022-12-09 17:18 UTC, sogamoso approved these changes

2022-12-09 17:21 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +        end
I mean `find` raises an unnecessary exception and we should avoid doing nothing with exceptions. Using `find_by(id: ...)&.activate!` is more intentional and avoids using an exception for flow control.

2022-12-09 17:22 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +        ::Companies::LeadBundleSubscription.with_pause_start_date.in_the_past.in_batches do |subscriptions_batch|
Yes, it makes sense to me now why it's the way it is.

2022-12-09 17:25 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +  include Sidekiq::Worker
Total nit, but [Sidekiq's maintainer now recommends](https://github.com/mperham/sidekiq/blob/936846ad705ab9bd0553d078a890bb68dc7a82d3/lib/sidekiq/worker_compatibility_alias.rb) using `Job` rather than `Worker`. `Worker` is just an alias for `Job`.

```suggestion
  include Sidekiq::Job
```

2022-12-19 15:26 UTC, baerbradford approved these changes

2022-12-19 16:53 UTC, bhanubhakta approved these changes

2023-01-26 12:34 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +        end
Hmmm... not sure I agree.

If the `LeadBundleSubscription` cannot be found, there's something wrong. And we should be notified that there's something wrong.

However, my code is actually wrong, because `Rails.error.handle` will swallow the error and only give a warning.

The solution is much simpler - get rid of the error handling entirely. Then `find` will blow up when the record can't be found (desired so we can debug why this happened) and Sentry will be notified.

2023-01-26 12:47 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +  include Sidekiq::Worker
Excellent point. Thank you! Done.

2023-01-26 15:37 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +        end
Works for me!

2023-01-26 15:40 UTC, bockets requested changes

2023-01-26 15:40 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +We had a [serious issue](https://www.notion.so/biggerpockets/Lead-bundle-subscriptions-incorrectly-pausing-or-resuming-298e9b328c834b148e3c79f12a686004) where user subscriptions were not being update
I don't think we'd want to share this link on a pattern that's public. Doesn't make sense to go into this much detail on it, this is just a best practice for how to write jobs.

2023-01-26 15:40 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +name: Make small, atomic Sidekiq workers
```suggestion
name: Make small, atomic Sidekiq jobs
```

2023-01-26 15:40 UTC, bockets commented on _patterns/make-small-atomic-sidekiq-workers.md
> +* Break down Sidekiq workers into the smallest functional unit you can
```suggestion
* Break down Sidekiq jobs into the smallest functional unit you can
```

2023-01-30 16:58 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +We had a [serious issue](https://www.notion.so/biggerpockets/Lead-bundle-subscriptions-incorrectly-pausing-or-resuming-298e9b328c834b148e3c79f12a686004) where user subscriptions were not being update
1b0dff0

2023-01-30 16:58 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +name: Make small, atomic Sidekiq workers
1b0dff0

2023-01-30 16:59 UTC, johngallagher commented on _patterns/make-small-atomic-sidekiq-workers.md
> +* Break down Sidekiq workers into the smallest functional unit you can
1b0dff0

2023-01-30 17:10 UTC, bockets approved these changes

2023-01-30 17:13 UTC, merged