Add pattern on design-by-extraction
BiggerPockets/patterns pull request #168
Opened 2023-05-05 20:54 UTC by bockets

2023-05-08 09:25 UTC, RenatoCoelho-BiggerPockets commented on _patterns/design-by-extraction.md
> +It's better to be intentional about global rewrites than to solve one problem one time with a one-off design.
Thanks for writing this @bockets, as a less experienced engineer, I believe I can gain much from this pattern. But in order for me to take advantage of it I need examples and more concrete guidelines so I can actually apply it.

2023-05-08 09:26 UTC, RenatoCoelho-BiggerPockets requested changes

2023-05-08 09:26 UTC, RenatoCoelho-BiggerPockets commented on _patterns/design-by-extraction.md
> +It's better to be intentional about global rewrites than to solve one problem one time with a one-off design.
Thanks for writing this @bockets, as a less experienced engineer, I believe I can gain much from this pattern. But in order for me to take advantage of it I need examples and more concrete guidelines so I can actually apply it.

2023-05-08 21:34 UTC, bockets commented on _patterns/design-by-extraction.md
> +It's better to be intentional about global rewrites than to solve one problem one time with a one-off design.
That's OK. Not all patterns are going to have concrete patterns, and they may not totally make sense to all engineers.

Here's a scenario where this pattern would apply:

1. Engineer Alice opens a PR. The PR includes a new abstraction Y that could be used to do X in some scenarios. Until now, X has been accomplished by just copying the same code over and over again.
1. Reviewer Bob sees that this new PR contains a new way of doing X. However, Bob also realizes that none of the copied versions of X have been replaced with Y. Y was only used on _new_ code.

In this scenario, Bob would call to Alice's attention that we've introduced Y while not actually removing any of the duplication of X. In an ideal world, Alice would have replaced all instances of X with Y such that there are no longer copied examples of X hanging around the code. But we don't live in an ideal world, and sometimes we do need to bring in new pattern Y in order to get off of X. Preferably, some attempt would be made by Alice to get rid of all of the copies of X and replace them with Y.

2023-05-09 09:41 UTC, karlentwistle commented on _patterns/design-by-extraction.md
> +It's better to be intentional about global rewrites than to solve one problem one time with a one-off design.
> Preferably, some attempt would be made by Alice to get rid of all of the copies of X and replace them with Y.

100% agree with this. Otherwise, we end up with multiple ways of achieving the same thing and it's unclear what the preferred approach is.

@bockets the sample you provided is extremely helpful to understand the pattern. I might be worth adding into the `_patterns/design-by-extraction.md`

2023-05-09 10:02 UTC, RenatoCoelho-BiggerPockets commented on _patterns/design-by-extraction.md
> +It's better to be intentional about global rewrites than to solve one problem one time with a one-off design.
Agree with Karl, that scenario helps the readability of the pattern and I would add it. I disagree that it's fine that a pattern doesn't make sense to all engineers, that leads to the pattern only being followed by those that needed it less instead of it helping elevate the whole team to a new standard.

That said, I am very thankful you're writing this.

2023-05-09 10:06 UTC, RenatoCoelho-BiggerPockets commented on _patterns/design-by-extraction.md
> +duplication.
I think you should mention the end goal here.

```suggestion
duplication, and make a plan to replace the other duplications with your new design.
```

2023-05-23 16:33 UTC, RenatoCoelho-BiggerPockets approved these changes
Thank you for addressing the feedback Aaron, be sure to fix this typo [here](https://github.com/BiggerPockets/patterns/pull/168/files#r1202680118) before merging

2023-05-23 16:33 UTC, RenatoCoelho-BiggerPockets approved these changes
Thank you for addressing the feedback Aaron, be sure to fix this typo [here](https://github.com/BiggerPockets/patterns/pull/168/files#r1202680118) before merging

2023-05-23 17:04 UTC, mgallagher0 approved these changes

2023-06-26 14:37 UTC, closed without merging

2023-06-26 14:37 UTC, bockets commented
Closing for now until I can revise