Add pattern on YARDoc
BiggerPockets/patterns pull request #172
Opened 2023-06-14 21:40 UTC by bockets

2023-06-14 21:40 UTC, bockets commented
I need to also add a section on auto-generated type-signature files from YARD.

2023-06-15 09:48 UTC, RenatoCoelho-BiggerPockets commented on _patterns/optionally-use-yardoc.md
> +Additionally, we're already using YARD whenever we create a `ViewComponent` preview.
We are using this in ViewComponent previews so it's clearer from our [lookbook](https://www.biggerpockets.com/lookbook) the variations for each component, not for the problem you are trying to solve here.

2023-06-15 09:57 UTC, RenatoCoelho-BiggerPockets commented on _patterns/optionally-use-yardoc.md
> +Ruby is a duck-typed programming language. The interpreter provides no guarantees that the code you write will actually
> that the code you write will actually execute in production

IMO when using duck-typed languages, tests are what ensure that, not comments.
I also have concerns with comments that lie to you because they have fallen behind the reality of the code.

2023-06-15 14:32 UTC, bockets commented on _patterns/optionally-use-yardoc.md
> +Ruby is a duck-typed programming language. The interpreter provides no guarantees that the code you write will actually
> I also have concerns with comments that lie to you because they have fallen behind the reality of the code.

Is this a concern rooted in experience at BP?

2023-06-15 14:33 UTC, bockets commented on _patterns/optionally-use-yardoc.md
> +Additionally, we're already using YARD whenever we create a `ViewComponent` preview.
Should I delete the line?

2023-06-15 16:55 UTC, bockets commented on _patterns/optionally-use-yardoc.md
> +Ruby is a duck-typed programming language. The interpreter provides no guarantees that the code you write will actually
These are not comments that explain what the code is doing. They're annotations to help other engineers reason about the expectations can be made. They're almost like design-by-contract but without the contract, so for me they're a good middle ground. I find them very helpful when architecting code so that my implementations don't become too complicated.

Bob Martin has a lot of good ideas and a lot of terrible ones. But _comments are a code smell_ is not one of his better ones IMO, that recommendation is way too broad. And there are plenty of people who think [recommendations in that book are not applicable any more](https://qntm.org/clean).

I also think it's a better argument to defer to teammates' experience rather than appeals to authority. Uncle Bob doesn't know our code or specific problems. His book is general recommendations. He may very well make the same determination if he was on our team, but he's not.

I'm not trying to force everyone get onboard this bandwagon. I'm trying to recommend something that I find useful to the broader team. It's OK to not like YARD.

2023-06-15 16:56 UTC, bockets commented on _patterns/optionally-use-yardoc.md
> +Additionally, we're already using YARD whenever we create a `ViewComponent` preview.
True enough.

2023-06-15 17:19 UTC, baerbradford requested changes
I think this pattern could benefit from some more explicit recommendation on when it's appropriate to comment in this manner and when it's not. You've placed it in the optional category and stated some benefits "when used well". I believe it's likely to simply be ignored without more direction.

Documenting like this makes sense in some cases, but, in my opinion, is not a good general recommendation to put all over our codebase.

Using this at the boundary of contexts / domains may make a lot of sense because we may have engineers trying to interface with an area of the codebase they aren't familiar with.

Using this when we have generated documentation that relies on it, like our lookbook, makes sense to me as well. I could see a future where we maybe do something like this to document an API utilized by a partner or 3rd party.

But as a general recommendation to potentially document anything and everything, I think we are making an administrative burden for ourselves without significant benefit. When used too liberally, I think comments like this can impact the readability of the codebase, duplicate information that's already evident from the code itself, and become outdated if not maintained.

2023-06-15 17:45 UTC, bockets commented
@baerbradford here's another example, where I want the argument name to not match the class name. This makes it slightly easier to pass the object through inside this method because it matches the name of the subsequently called class:

```
class DeliverNotificationPushNotificationsJob < ApplicationJob
  # @param subject [Notification]
  def perform(subject)
    subject.social_user.push_subscriptions.find_each do |push_subscription|
      DeliverPushNotificationJob.perform_later(push_subscription:, subject:)
    end
  end
end
```

2023-06-15 18:42 UTC, baerbradford commented
> @baerbradford here's another example, where I want the argument name to not match the class name. This makes it slightly easier to pass the object through inside this method because it matches the name of the subsequently called class:
> 
> ```ruby
> class DeliverNotificationPushNotificationsJob < ApplicationJob
>   # @param subject [Notification]
>   def perform(subject)
>     subject.social_user.push_subscriptions.find_each do |push_subscription|
>       DeliverPushNotificationJob.perform_later(push_subscription:, subject:)
>     end
>   end
> end
> ```
> 
> Without this annotation, it's not obvious what class `subject` should be.

@bockets, That does seem like it could be a fine use case for it, yes. It'd be clear to consumers of those classes what was expected based on documenting it that way.

I might argue, though, writing this code with duck-typing and a more defensive style might be more expressive about what you're expecting from the parameter while meaningfully enforcing it. It could also eliminate the need to maintain a comment as the code changes to avoid the code and documentation drifting apart.

```ruby
class DeliverNotificationPushNotificationsJob < ApplicationJob
  def perform(subject)
    unless subject.respond_to?(:subject_behavior_1) && subject.respond_to?(:subject_behavior_2)
      raise ArgumentError, "Subject does not meet the expected interface"
    end

    subject.social_user.push_subscriptions.find_each do |push_subscription|
      DeliverPushNotificationJob.perform_later(push_subscription:, subject:)
    end
  end
end
```

2023-06-15 21:19 UTC, bockets commented
> > @baerbradford here's another example, where I want the argument name to not match the class name. This makes it slightly easier to pass the object through inside this method because it matches the name of the subsequently called class:
> > ```ruby
> > class DeliverNotificationPushNotificationsJob < ApplicationJob
> >   # @param subject [Notification]
> >   def perform(subject)
> >     subject.social_user.push_subscriptions.find_each do |push_subscription|
> >       DeliverPushNotificationJob.perform_later(push_subscription:, subject:)
> >     end
> >   end
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Without this annotation, it's not obvious what class `subject` should be.
> 
> @bockets, That does seem like it could be a fine use case for it, yes. It'd be clear to consumers of those classes what was expected based on documenting it that way.
> 
> I might argue, though, writing this code with duck-typing and a more defensive style might be more expressive about what you're expecting from the parameter while meaningfully enforcing it. It could also eliminate the need to maintain a comment as the code changes to avoid the code and documentation drifting apart.
> 
> ```ruby
> class DeliverNotificationPushNotificationsJob < ApplicationJob
>   def perform(subject)
>     unless subject.respond_to?(:subject_behavior_1) && subject.respond_to?(:subject_behavior_2)
>       raise ArgumentError, "Subject does not meet the expected interface"
>     end
> 
>     subject.social_user.push_subscriptions.find_each do |push_subscription|
>       DeliverPushNotificationJob.perform_later(push_subscription:, subject:)
>     end
>   end
> end
> ```

Thanks for the alternative. I'll consider it and get back to you.

2023-06-26 15:37 UTC, johngallagher approved these changes
Fantastic idea. I've never used this. This would have saved me so much time. Thank you @bockets!

2023-06-26 15:45 UTC, johngallagher commented
> > @baerbradford here's another example, where I want the argument name to not match the class name. This makes it slightly easier to pass the object through inside this method because it matches the name of the subsequently called class:
> > ```ruby
> > class DeliverNotificationPushNotificationsJob < ApplicationJob
> >   # @param subject [Notification]
> >   def perform(subject)
> >     subject.social_user.push_subscriptions.find_each do |push_subscription|
> >       DeliverPushNotificationJob.perform_later(push_subscription:, subject:)
> >     end
> >   end
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Without this annotation, it's not obvious what class `subject` should be.
> 
> @bockets, That does seem like it could be a fine use case for it, yes. It'd be clear to consumers of those classes what was expected based on documenting it that way.
> 
> I might argue, though, writing this code with duck-typing and a more defensive style might be more expressive about what you're expecting from the parameter while meaningfully enforcing it. It could also eliminate the need to maintain a comment as the code changes to avoid the code and documentation drifting apart.
> 
> ```ruby
> class DeliverNotificationPushNotificationsJob < ApplicationJob
>   def perform(subject)
>     unless subject.respond_to?(:subject_behavior_1) && subject.respond_to?(:subject_behavior_2)
>       raise ArgumentError, "Subject does not meet the expected interface"
>     end
> 
>     subject.social_user.push_subscriptions.find_each do |push_subscription|
>       DeliverPushNotificationJob.perform_later(push_subscription:, subject:)
>     end
>   end
> end
> ```

If we're going to do this for every argument, we'll end up with a huge amount of boilerplate defensive code. If we're going to go down this route, we should invest heavily in Sorbet instead IMO.

The advantage of @bockets 's suggestion is that we're gradually introducing **thinking** about types into the codebase.

We can try YARDoc out with minimal friction or disruption and just see how we get on.

Maybe no-one will use it. Maybe a few will use it. Maybe we'll find use cases that are more important than others.

I think it's difficult to predict how this will be used and I'd like us to give it a go and revisit in a month.

2023-06-28 19:52 UTC, bockets commented
A PR that adds YARDoc to the development Procfile: https://github.com/BiggerPockets/biggerpockets/pull/18290

2023-06-29 14:18 UTC, bockets commented
Here's a example from our code where annotated arguments would really help. It was from part of the code that I am unfamiliar with, but want to call from a new place:

```ruby
def initialize(market:, current_user: nil)
  # ...
end
```

The `current_user` object is pretty obvious, but what is the `market` argument supposed to be? I have to go look up examples of what calls this to know what it expects to take.

2023-07-31 15:39 UTC, mgallagher0 approved these changes

2023-07-31 15:42 UTC, sogamoso approved these changes

2023-07-31 15:43 UTC, Hafiz-ahmed-dev approved these changes

2023-07-31 15:46 UTC, bockets commented
Look into linting this with Rubocop

2023-08-01 10:17 UTC, johngallagher approved these changes

2023-08-28 03:17 UTC, kxhitiz approved these changes

2023-08-28 15:21 UTC, merged