Add preferred http client
BiggerPockets/patterns pull request #193
Opened 2024-02-23 19:22 UTC by petershutt

When using an http client in the app, use Faraday when possible. 
1. It is faster than Httpparty (which is the other http gem in our app currently)
2. It is a more flexible gem. It acts as a middleware which then can wrap multiple adapters
3. We can benefit from having a default http client in our app. We can set one open/read timeout and other configuration options.

2024-02-23 19:25 UTC, bockets commented on _patterns/prefer_faraday_as_http_client.md
> +1. It is faster
[citation needed]

2024-02-23 19:26 UTC, bockets requested changes
This needs to speak to the retry logic handling as I believe that's the primary reason to use faraday vs something else.

2024-02-23 21:47 UTC, petershutt commented on _patterns/prefer_faraday_as_http_client.md
> +2. It has a retry ability at the middleware layer
How does it look now?

2024-02-26 11:41 UTC, karlentwistle approved these changes

2024-02-26 11:42 UTC, johngallagher commented on _patterns/prefer_faraday_as_http_client.md
> +Httpparty has to be configured at a request level so request options have to be explicitly
Nitpick - Fix typo in HTTParty.

```suggestion
HTTParty has to be configured at a request level so request options have to be explicitly
```

2024-02-26 11:47 UTC, johngallagher commented on _patterns/prefer_faraday_as_http_client.md
> +response = ExtendedHttparty.get('http://api.stackexchange.com/2.2/questions?site=stackoverflow', tries: 5)
Consider making code example more consistent and concise:

```suggestion
require 'httparty'

# GET request
response = HTTParty.get('https://jsonplaceholder.typicode.com/posts/1', timeout: 5)

# GET request with retry
response = ExtendedHttparty.get('https://jsonplaceholder.typicode.com/posts/1', tries: 5)
```

2024-02-26 11:50 UTC, johngallagher commented on _patterns/prefer_faraday_as_http_client.md
> +con.get('https://jsonplaceholder.typicode.com/posts/1')
```suggestion
require 'faraday'

# GET request

Faraday.get('https://jsonplaceholder.typicode.com/posts/1')

# GET request with retry

require 'faraday/retry'

conn = Faraday.new do |f|
  f.request :retry, {
    max: 2,
    interval: 0.05,
    interval_randomness: 0.5,
    backoff_factor: 2,
    timeout: 2,
  }
end

conn.get('https://jsonplaceholder.typicode.com/posts/1')
```

2024-02-26 11:51 UTC, johngallagher commented on _patterns/prefer_faraday_as_http_client.md
> +```
Remove typo:

```suggestion
```

2024-02-26 11:53 UTC, johngallagher commented on _patterns/prefer_faraday_as_http_client.md
> +Retries can be set up with the `FaradayMiddleware::Retry` middleware.
```suggestion
* Global configuration options - open/read timeout, retries, etc.
* Configure retries using `FaradayMiddleware::Retry`
```

2024-02-26 14:11 UTC, petershutt commented on _patterns/prefer_faraday_as_http_client.md
> +Httpparty has to be configured at a request level so request options have to be explicitly
Removed the extra 'p' but I think it is all lowercase: `httparty`

2024-02-26 14:29 UTC, bockets commented
Closes #193

2024-02-26 16:02 UTC, kxhitiz commented on _patterns/prefer_faraday_as_http_client.md
> +    timeout: 2,
Since we are using the value `5` for retries and timeouts for the bad version of this code block, what do you think of using same value in here as well?

```suggestion
    max: 5,
    interval: 0.05,
    interval_randomness: 0.5,
    backoff_factor: 2,
    timeout: 5,
```

2024-02-26 16:06 UTC, johngallagher commented on _patterns/prefer_faraday_as_http_client.md
> +External gem for retrying requests with httparty
```suggestion
```

2024-02-26 16:07 UTC, johngallagher commented on _patterns/prefer_faraday_as_http_client.md
> +conn.get('https://jsonplaceholder.typicode.com/posts/1')
Small tweak for consistency:

```suggestion
require 'faraday'

# GET request
Faraday.get('https://jsonplaceholder.typicode.com/posts/1')

# GET request with retry
require 'faraday/retry'
conn = Faraday.new do |f|
  f.request :retry, {
    max: 5,
    interval: 0.05,
    interval_randomness: 0.5,
    backoff_factor: 2,
    timeout: 5,
  }
end
conn.get('https://jsonplaceholder.typicode.com/posts/1')
```

2024-02-26 16:51 UTC, cernivec approved these changes

2024-02-26 16:51 UTC, kxhitiz approved these changes

2024-02-26 17:02 UTC, bockets approved these changes

2024-02-27 08:24 UTC, johngallagher approved these changes

2024-03-25 14:39 UTC, baerbradford approved these changes

2024-03-25 15:19 UTC, sogamoso approved these changes

2024-03-25 16:23 UTC, merged